server:
  port: 8081
# DataSource Config
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.1.131:3306/hzh_vueadmin?useOldAliasMetadataBehavior=true&useSSL=false&serverTimezone=GMT
    #腾讯云服务器
    #url: jdbc:mysql://42.192.223.230:3306/java_mail?useOldAliasMetadataBehavior=true&useSSL=false&serverTimezone=GMT
    username: root
    password: 5q6W7e8R

  redis:
    # redis数据库索引(默认为0)，我们使用索引为3的数据库，避免和其他数据库冲突
    database: 0
    # redis服务器地址（默认为loaclhost）
    host: 192.168.1.131
    # redis端口（默认为6379）
    port: 6379
    # redis访问密码（默认为空）
    #password: pwd123
    # redis连接超时时间（单位毫秒）
    #timeout: 0
    # redis连接池配置
    pool:
      # 最大可用连接数（默认为8，负数表示无限）
      max-active: 8
      #最大空闲连接数（默认为8，负数表示无限）
      max-idle: 8
      # 最小空闲连接数（默认为0，该值只有为正数才有用）
      min-idle: 0
      # 从连接池中获取连接最大等待时间（默认为-1，单位为毫秒，负数表示无限）
      max-wait: -1



mybatis-plus:
  mapper-locations: classpath*:/mapper/**Mapper.xml
hzh:
  jwt:
    header: Authorization
    expire: 604800 #7天，秒单位
    secret: ji8n3439n439n43ld9ne9343fdfer49h